name: Ingest to Supabase (Hourly)

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test DB connectivity
        run: npm run test:db
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Migrate schema
        run: node --env-file=.env ./dist/src/index.js migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Ingest CourtListener
        run: node --env-file=.env ./dist/src/index.js ingest
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
