name: Ingest & Deploy (Hourly)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Ingest
        env:
          PROPUBLICA_API_KEY: ${{ secrets.PROPUBLICA_API_KEY }}
          OPENSTATES_API_KEY: ${{ secrets.OPENSTATES_API_KEY }}
        run: npm run ingest

      - name: Build & Export
        run: |
          npm run build:pages
          npm run export:pages

      - name: Publish to /docs
        run: |
          rm -rf docs && mkdir -p docs && cp -r out/* docs/ && touch docs/.nojekyll
          git add -A docs
          git -c user.name="gh-actions" -c user.email="actions@users.noreply.github.com" commit -m "Auto deploy: $(date -u +'%Y-%m-%d %H:%M:%SZ')" || echo "No changes"
          git push
